"use client"

import { FileText, Table2, Presentation, ArrowRight, Sparkles, FileKey2, CalendarDays, Code2, Zap, ShieldCheck, Workflow } from "lucide-react"
import { useSuite, type AppKey } from "@/components/suite-context"
import { MODELS } from "@/lib/ai-service"

const CARDS: {
  key: AppKey
  title: string
  desc: string
  icon: typeof FileText
  color: string
  copilot: string
}[] = [
  {
    key: "word",
    title: "notjustaword",
    desc: "A focused writing canvas with a multi-AI Copilot that drafts directly at your cursor.",
    icon: FileText,
    color: "#4285f4",
    copilot: "AI Writer",
  },
  {
    key: "sheet",
    title: "notjustasheet",
    desc: "A live spreadsheet with formula evaluation and an AI Analyst that reads your grid.",
    icon: Table2,
    color: "#34a853",
    copilot: "AI Analyst",
  },
  {
    key: "slide",
    title: "notjustaslide",
    desc: "Type a prompt, get a structured corporate deck generated by your chosen engine.",
    icon: Presentation,
    color: "#fbbc04",
    copilot: "Slide Copilot",
  },
  {
    key: "pdf",
    title: "notjustanpdf",
    desc: "Review, annotate, and safely edit PDFs with a focused document workspace.",
    icon: FileKey2,
    color: "#fb7185",
    copilot: "PDF workspace",
  },
  {
    key: "project",
    title: "Project Premium Pro",
    desc: "Turn a brief into milestones, owners, dependencies, and a clear delivery plan.",
    icon: CalendarDays,
    color: "#a78bfa",
    copilot: "AI Planner",
  },
  {
    key: "code",
    title: "notjustacode",
    desc: "Build HTML, CSS, and JavaScript with a live preview and export-ready output.",
    icon: Code2,
    color: "#67e8f9",
    copilot: "Code assistant",
  },
  {
    key: "visio",
    title: "notjustanvisio",
    desc: "Map systems, processes, spaces, and complex ideas with editable vector diagrams.",
    icon: Workflow,
    color: "#5eead4",
    copilot: "Diagram workspace",
  },
]

export function HomeDashboard() {
  const { setActiveApp, activeModel, variants } = useSuite()
  const m = MODELS[activeModel]
  const variantLabel = m.variants.find((v) => v.id === variants[activeModel])?.label

  return (
    <div className="h-full overflow-auto scroll-thin">
      <div className="mx-auto max-w-5xl px-6 py-10 lg:py-16">
        <div
          className="mb-2 inline-flex items-center gap-2 rounded-full border border-border px-3 py-1 text-xs"
          style={{ color: m.accent }}
        >
          <span className="size-1.5 rounded-full animate-pulse-glow" style={{ background: m.accent }} />
          Routing through {m.brand} · {variantLabel}
        </div>

        <h1 className="text-balance text-4xl font-semibold tracking-tight lg:text-5xl">
          One office.<br />
          <span className="text-muted-foreground">Every AI model.</span>
        </h1>
        <p className="mt-4 max-w-xl text-pretty leading-relaxed text-muted-foreground">
          A premium cloud productivity suite with a universal AI router built into its core. Switch between ChatGPT,
          Claude, Gemini and Grok globally — your documents, sheets and decks all share the same engine.
        </p>

        <div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
          <div className="col-span-full flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-primary/20 bg-primary/5 px-4 py-3">
            <div className="flex items-center gap-3">
              <span className="flex size-8 items-center justify-center rounded-lg bg-primary/15 text-primary"><Zap className="size-4" /></span>
              <div><p className="text-sm font-medium">Start with a workspace</p><p className="text-xs text-muted-foreground">Your work stays in one shared suite.</p></div>
            </div>
            <span className="flex items-center gap-1.5 text-xs text-emerald-300"><ShieldCheck className="size-3.5" /> Private by default</span>
          </div>
          {CARDS.map((c) => {
            const Icon = c.icon
            return (
              <button
                key={c.key}
                onClick={() => setActiveApp(c.key)}
                className="group flex flex-col rounded-2xl border border-border bg-card p-5 text-left transition-all hover:-translate-y-0.5 hover:border-foreground/20"
              >
                <span
                  className="flex size-11 items-center justify-center rounded-xl"
                  style={{ color: c.color, background: `${c.color}1a` }}
                >
                  <Icon className="size-5" />
                </span>
                <h3 className="mt-4 font-medium">{c.title}</h3>
                <p className="mt-1 flex-1 text-sm leading-relaxed text-muted-foreground">{c.desc}</p>
                <span className="mt-4 flex items-center gap-1.5 text-sm font-medium text-foreground">
                  <Sparkles className="size-3.5" style={{ color: c.color }} />
                  {c.copilot}
                  <ArrowRight className="size-3.5 transition-transform group-hover:translate-x-0.5" />
                </span>
              </button>
            )
          })}
        </div>

        <div className="mt-8 rounded-2xl border border-border bg-card/50 p-5">
          <div className="flex flex-wrap items-center justify-between gap-2"><div><h2 className="text-sm font-semibold">Suite at a glance</h2><p className="mt-1 text-xs text-muted-foreground">Six focused workspaces, one active AI engine.</p></div><span className="rounded-full border border-border px-2.5 py-1 text-[11px] text-muted-foreground">{CARDS.length} workspaces</span></div>
          <div className="mt-5 grid gap-3 sm:grid-cols-3">
            {[{ label: "Create", value: "Documents, sheets, decks", key: "word" as AppKey }, { label: "Plan", value: "Tasks and milestones", key: "project" as AppKey }, { label: "Build", value: "Code and live preview", key: "code" as AppKey }].map((item) => <button key={item.label} onClick={() => setActiveApp(item.key)} className="rounded-xl border border-border/70 bg-background/40 p-3 text-left transition-colors hover:border-primary/40 hover:bg-primary/5"><p className="text-xs font-medium text-primary">{item.label}</p><p className="mt-1 text-sm">{item.value}</p><p className="mt-2 text-[11px] text-muted-foreground">Open workspace <ArrowRight className="ml-1 inline size-3" /></p></button>)}
          </div>
        </div>

        <div className="mt-6 grid gap-3 rounded-2xl border border-border bg-card/50 p-5 sm:grid-cols-4">
          {Object.values(MODELS).map((model) => (
            <div key={model.id} className="flex items-center gap-2.5">
              <span className="size-2.5 rounded-full" style={{ background: model.accent }} />
              <div className="leading-tight">
                <div className="text-sm font-medium">{model.brand}</div>
                <div className="text-[11px] text-muted-foreground">{model.vendor}</div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  )
}
