"use client"

import { FileText, Table2, Presentation, ArrowRight, Sparkles } from "lucide-react"
import { useSuite, type AppKey } from "@/components/suite-context"
import { MODELS } from "@/lib/ai-service"

const CARDS: {
  key: AppKey
  title: string
  desc: string
  icon: typeof FileText
  color: string
  copilot: string
}[] = [
  {
    key: "word",
    title: "notjustaword",
    desc: "A focused writing canvas with a multi-AI Copilot that drafts directly at your cursor.",
    icon: FileText,
    color: "#4285f4",
    copilot: "AI Writer",
  },
  {
    key: "sheet",
    title: "notjustasheet",
    desc: "A live spreadsheet with formula evaluation and an AI Analyst that reads your grid.",
    icon: Table2,
    color: "#34a853",
    copilot: "AI Analyst",
  },
  {
    key: "slide",
    title: "notjustaslide",
    desc: "Type a prompt, get a structured corporate deck generated by your chosen engine.",
    icon: Presentation,
    color: "#fbbc04",
    copilot: "Slide Copilot",
  },
]

export function HomeDashboard() {
  const { setActiveApp, activeModel, variants } = useSuite()
  const m = MODELS[activeModel]
  const variantLabel = m.variants.find((v) => v.id === variants[activeModel])?.label

  return (
    <div className="h-full overflow-auto scroll-thin">
      <div className="mx-auto max-w-5xl px-6 py-10 lg:py-16">
        <div
          className="mb-2 inline-flex items-center gap-2 rounded-full border border-border px-3 py-1 text-xs"
          style={{ color: m.accent }}
        >
          <span className="size-1.5 rounded-full animate-pulse-glow" style={{ background: m.accent }} />
          Routing through {m.brand} · {variantLabel}
        </div>

        <h1 className="text-balance text-4xl font-semibold tracking-tight lg:text-5xl">
          One office.<br />
          <span className="text-muted-foreground">Every AI model.</span>
        </h1>
        <p className="mt-4 max-w-xl text-pretty leading-relaxed text-muted-foreground">
          A premium cloud productivity suite with a universal AI router built into its core. Switch between ChatGPT,
          Claude, Gemini and Grok globally — your documents, sheets and decks all share the same engine.
        </p>

        <div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
          {CARDS.map((c) => {
            const Icon = c.icon
            return (
              <button
                key={c.key}
                onClick={() => setActiveApp(c.key)}
                className="group flex flex-col rounded-2xl border border-border bg-card p-5 text-left transition-all hover:-translate-y-0.5 hover:border-foreground/20"
              >
                <span
                  className="flex size-11 items-center justify-center rounded-xl"
                  style={{ color: c.color, background: `${c.color}1a` }}
                >
                  <Icon className="size-5" />
                </span>
                <h3 className="mt-4 font-medium">{c.title}</h3>
                <p className="mt-1 flex-1 text-sm leading-relaxed text-muted-foreground">{c.desc}</p>
                <span className="mt-4 flex items-center gap-1.5 text-sm font-medium text-foreground">
                  <Sparkles className="size-3.5" style={{ color: c.color }} />
                  {c.copilot}
                  <ArrowRight className="size-3.5 transition-transform group-hover:translate-x-0.5" />
                </span>
              </button>
            )
          })}
        </div>

        <div className="mt-10 grid gap-3 rounded-2xl border border-border bg-card/50 p-5 sm:grid-cols-4">
          {Object.values(MODELS).map((model) => (
            <div key={model.id} className="flex items-center gap-2.5">
              <span className="size-2.5 rounded-full" style={{ background: model.accent }} />
              <div className="leading-tight">
                <div className="text-sm font-medium">{model.brand}</div>
                <div className="text-[11px] text-muted-foreground">{model.vendor}</div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  )
}
