"use client"

import { useMemo, useState } from "react"
import { CalendarDays, CheckCircle2, ChevronDown, Circle, Flag, LayoutList, Plus, Sparkles, Users, WandSparkles } from "lucide-react"
import { useSuite, type ProjectTask } from "@/components/suite-context"
import { MODELS, streamMessage } from "@/lib/ai-service"
import { cn } from "@/lib/utils"

const seedTasks: ProjectTask[] = [
  { id: "T1", name: "Define project vision", phase: "Initiation", owner: "Leadership", duration: 3, start: "2026-10-05", status: "In progress", dependency: "", milestone: true, description: "Align the team on outcomes and decision owners." },
  { id: "T2", name: "Create project charter", phase: "Planning", owner: "Product", duration: 4, start: "2026-10-08", status: "Ready", dependency: "T1", milestone: false, description: "Document scope, success metrics, budget, and risks." },
  { id: "T3", name: "Map requirements", phase: "Planning", owner: "Design", duration: 6, start: "2026-10-12", status: "Not started", dependency: "T2", milestone: false, description: "Turn stakeholder needs into testable requirements." },
  { id: "T4", name: "Build first increment", phase: "Execution", owner: "Engineering", duration: 10, start: "2026-10-20", status: "Not started", dependency: "T3", milestone: false, description: "Deliver the smallest valuable working slice." },
  { id: "T5", name: "Quality review", phase: "Execution", owner: "Operations", duration: 5, start: "2026-11-02", status: "Not started", dependency: "T4", milestone: false, description: "Validate acceptance criteria and resolve critical defects." },
  { id: "T6", name: "Launch readiness", phase: "Launch", owner: "Marketing", duration: 4, start: "2026-11-09", status: "Not started", dependency: "T5", milestone: true, description: "Prepare communications, training, and release checklist." },
]

export function ProjectApp() {
  const { activeModel, variants, apiKeys, projectTasks, setProjectTasks, updateProjectTask } = useSuite()
  const [brief, setBrief] = useState("Plan a premium launch for our next product release")
  const [view, setView] = useState<"gantt" | "tasks" | "resources">("gantt")
  const [busy, setBusy] = useState(false)
  const [notice, setNotice] = useState("")
  const tasks = projectTasks.length ? projectTasks : seedTasks
  const maxDays = Math.max(...tasks.map((task) => task.duration + tasks.indexOf(task) * 3), 1)

  const plan = async () => {
    setBusy(true); setNotice("")
    const raw = await streamMessage({ model: activeModel, variant: variants[activeModel], apiKeys, mode: "plan", prompt: brief }, () => {})
    try {
      const parsed = JSON.parse(raw) as ProjectTask[]
      setProjectTasks(parsed)
      setNotice(`Plan generated by ${MODELS[activeModel].brand}. Review owners, dependencies, and dates below.`)
    } catch {
      setNotice("The planner returned a readable plan, but it could not be imported automatically. Try again with a shorter brief.")
    } finally { setBusy(false) }
  }

  const addTask = () => setProjectTasks([...tasks, { id: `T${tasks.length + 1}`, name: "New project task", phase: "Execution", owner: "Unassigned", duration: 3, start: "2026-11-13", status: "Not started", dependency: tasks.at(-1)?.id ?? "", milestone: false, description: "Add acceptance criteria and a clear owner." }])
  const progress = Math.round(tasks.filter((t) => t.status === "Complete").length / tasks.length * 100)
  const owners = useMemo(() => Array.from(new Set(tasks.map((task) => task.owner))), [tasks])

  return <div className="flex h-full min-h-0 flex-col bg-background">
    <header className="flex shrink-0 items-center justify-between border-b border-border px-6 py-4">
      <div><div className="flex items-center gap-2"><div className="flex size-9 items-center justify-center rounded-xl bg-primary/15 text-primary"><CalendarDays className="size-5" /></div><div><h1 className="text-lg font-semibold tracking-tight">Project Premium Pro</h1><p className="text-xs text-muted-foreground">Project planning, dependencies, resources, and delivery control</p></div></div></div>
      <div className="flex items-center gap-2"><span className="rounded-full border border-border bg-card px-3 py-1.5 text-xs text-muted-foreground">{tasks.length} tasks</span><button onClick={addTask} className="flex items-center gap-2 rounded-lg bg-primary px-3 py-2 text-xs font-medium text-primary-foreground"><Plus className="size-3.5" />New task</button></div>
    </header>
    <div className="flex min-h-0 flex-1 flex-col overflow-hidden">
      <div className="flex shrink-0 items-center gap-1 border-b border-border px-6 py-2"><div className="flex rounded-lg border border-border bg-card p-0.5">{([['gantt','Gantt chart'],['tasks','Task board'],['resources','Resources']] as const).map(([key,label]) => <button key={key} onClick={() => setView(key)} className={cn("rounded-md px-3 py-1.5 text-xs transition-colors", view === key ? "bg-accent text-foreground" : "text-muted-foreground hover:text-foreground")}>{label}</button>)}</div><div className="ml-auto flex items-center gap-3 text-xs text-muted-foreground"><span className="flex items-center gap-1"><span className="size-2 rounded-full bg-primary" />{progress}% complete</span><span>{owners.length} owners</span></div></div>
      <div className="grid min-h-0 flex-1 grid-cols-[minmax(0,1fr)_300px]">
        <main className="min-w-0 overflow-auto p-6 scroll-thin">
          {view === "gantt" && <div className="min-w-[760px] overflow-hidden rounded-xl border border-border bg-card"><div className="grid grid-cols-[280px_1fr] border-b border-border bg-accent/30 text-xs font-medium"><div className="px-4 py-3">Task name</div><div className="grid grid-cols-6"><span className="border-l border-border px-3 py-3">Oct 05</span><span className="border-l border-border px-3 py-3">Oct 12</span><span className="border-l border-border px-3 py-3">Oct 19</span><span className="border-l border-border px-3 py-3">Oct 26</span><span className="border-l border-border px-3 py-3">Nov 02</span><span className="border-l border-border px-3 py-3">Nov 09</span></div></div>{tasks.map((task, i) => <div key={task.id} className="grid grid-cols-[280px_1fr] border-b border-border last:border-0"><div className="flex items-center gap-3 px-4 py-3"><button onClick={() => updateProjectTask(task.id, { status: task.status === "Complete" ? "Not started" : "Complete" })}>{task.status === "Complete" ? <CheckCircle2 className="size-4 text-primary" /> : <Circle className="size-4 text-muted-foreground" />}</button><div className="min-w-0"><input value={task.name} onChange={(e) => updateProjectTask(task.id, { name: e.target.value })} className="w-full bg-transparent text-sm outline-none" /><p className="text-[11px] text-muted-foreground">{task.id} · {task.owner} · {task.dependency ? `after ${task.dependency}` : "no dependency"}</p></div>{task.milestone && <Flag className="ml-auto size-3.5 shrink-0 text-amber-400" />}</div><div className="relative grid grid-cols-6 items-center bg-[linear-gradient(to_right,transparent_0,transparent_calc(16.666%-1px),hsl(var(--border))_16.666%,transparent_calc(16.666%+1px))]">{Array.from({length: 6}).map((_, j) => <span key={j} className="h-full border-l border-border/50" />)}<div className={cn("absolute top-1/2 h-6 -translate-y-1/2 rounded-md px-2 text-[10px] font-medium leading-6 text-primary-foreground shadow-sm", task.status === "Complete" ? "bg-primary" : task.status === "In progress" ? "bg-primary/75" : "bg-muted-foreground/60")} style={{ left: `${Math.min(i * 12, 70)}%`, width: `${Math.max(task.duration * 3.5, 9)}%` }}>{task.duration}d</div></div></div>)}</div>}
          {view === "tasks" && <div className="grid gap-4 md:grid-cols-3">{["In progress","Ready","Not started"].map((status) => <div key={status} className="rounded-xl border border-border bg-card p-3"><div className="mb-3 flex items-center justify-between"><h2 className="text-sm font-medium">{status}</h2><span className="rounded-full bg-accent px-2 py-0.5 text-[11px] text-muted-foreground">{tasks.filter(t => t.status === status).length}</span></div><div className="flex flex-col gap-2">{tasks.filter(t => t.status === status).map(task => <div key={task.id} className="rounded-lg border border-border/70 bg-background p-3"><p className="text-sm font-medium">{task.name}</p><p className="mt-1 text-[11px] text-muted-foreground">{task.owner} · {task.duration} days</p></div>)}</div></div>)}</div>}
          {view === "resources" && <div className="grid gap-3 md:grid-cols-2">{owners.map(owner => <div key={owner} className="rounded-xl border border-border bg-card p-4"><div className="flex items-center gap-3"><div className="flex size-9 items-center justify-center rounded-lg bg-primary/10 text-primary"><Users className="size-4" /></div><div><p className="text-sm font-medium">{owner}</p><p className="text-xs text-muted-foreground">{tasks.filter(t => t.owner === owner).length} assigned tasks</p></div></div><div className="mt-3 h-1.5 rounded-full bg-accent"><div className="h-full rounded-full bg-primary" style={{ width: `${Math.min(tasks.filter(t => t.owner === owner).length * 30, 100)}%` }} /></div></div>)}</div>}
        </main>
        <aside className="flex min-h-0 flex-col border-l border-border bg-card/30"><div className="border-b border-border p-5"><div className="flex items-center gap-2"><WandSparkles className="size-4 text-primary" /><h2 className="text-sm font-semibold">AI project planner</h2></div><p className="mt-1 text-xs leading-relaxed text-muted-foreground">Describe the outcome. {MODELS[activeModel].brand} will create phases, dependencies, owners, durations, and milestones.</p></div><div className="flex flex-1 flex-col gap-3 p-5"><textarea value={brief} onChange={(e) => setBrief(e.target.value)} className="min-h-32 resize-none rounded-lg border border-border bg-background p-3 text-sm outline-none ring-primary/30 placeholder:text-muted-foreground focus:ring-2" placeholder="Describe the project you want to plan..." /><button disabled={busy} onClick={plan} className="flex items-center justify-center gap-2 rounded-lg bg-primary px-3 py-2.5 text-sm font-medium text-primary-foreground disabled:opacity-60">{busy ? <Sparkles className="size-4 animate-pulse" /> : <Sparkles className="size-4" />}{busy ? "Building plan..." : `Plan with ${MODELS[activeModel].brand}`}</button>{notice && <div className="rounded-lg border border-primary/20 bg-primary/5 p-3 text-xs leading-relaxed text-muted-foreground">{notice}</div>}<div className="mt-auto rounded-lg border border-border bg-background p-3"><div className="flex items-center gap-2 text-xs font-medium"><LayoutList className="size-3.5 text-primary" /> Planning checklist</div><ul className="mt-2 flex flex-col gap-2 text-[11px] text-muted-foreground"><li>Dependencies are visible on every task.</li><li>Flag milestones before setting a baseline.</li><li>Give every task one accountable owner.</li></ul></div></div></aside>
      </div>
    </div>
  </div>
}
